//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseManagementEntities : DbContext
    {
        public CourseManagementEntities()
            : base("name=CourseManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Fee_Payment_Info> tbl_Fee_Payment_Info { get; set; }
        public virtual DbSet<tbl_Course_Detail> tbl_Course_Detail { get; set; }
        public virtual DbSet<tbl_Course_Video> tbl_Course_Video { get; set; }
        public virtual DbSet<tbl_Emp_Attempted_Stud> tbl_Emp_Attempted_Stud { get; set; }
        public virtual DbSet<tbl_Emp_Info> tbl_Emp_Info { get; set; }
        public virtual DbSet<tbl_Emp_Job_Ad> tbl_Emp_Job_Ad { get; set; }
        public virtual DbSet<tbl_Emp_Job_Ad_Skills> tbl_Emp_Job_Ad_Skills { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
        public virtual DbSet<tbl_Master> tbl_Master { get; set; }
        public virtual DbSet<tbl_Sub_Master> tbl_Sub_Master { get; set; }
        public virtual DbSet<tbl_Stud_Assignment_Answers> tbl_Stud_Assignment_Answers { get; set; }
        public virtual DbSet<tbl_Stud_Assignment_Info> tbl_Stud_Assignment_Info { get; set; }
        public virtual DbSet<tbl_Stud_Assignment_Project_Answers> tbl_Stud_Assignment_Project_Answers { get; set; }
        public virtual DbSet<tbl_Stud_Certificate> tbl_Stud_Certificate { get; set; }
        public virtual DbSet<tbl_Stud_Course_Regd> tbl_Stud_Course_Regd { get; set; }
        public virtual DbSet<tbl_Stud_Favourites_Vd> tbl_Stud_Favourites_Vd { get; set; }
        public virtual DbSet<tbl_Stud_Job_Exp_Info> tbl_Stud_Job_Exp_Info { get; set; }
        public virtual DbSet<tbl_Stud_Notes> tbl_Stud_Notes { get; set; }
        public virtual DbSet<tbl_Stud_Personal_Info> tbl_Stud_Personal_Info { get; set; }
        public virtual DbSet<tbl_Stud_Resume> tbl_Stud_Resume { get; set; }
        public virtual DbSet<tbl_Stud_Skill_Set> tbl_Stud_Skill_Set { get; set; }
        public virtual DbSet<tbl_Stud_Viewed_Vd> tbl_Stud_Viewed_Vd { get; set; }
        public virtual DbSet<tbl_Trnr_Assignment_Master> tbl_Trnr_Assignment_Master { get; set; }
        public virtual DbSet<tbl_Trnr_Assignment_Questions> tbl_Trnr_Assignment_Questions { get; set; }
        public virtual DbSet<tbl_Trnr_Job_Exp_Info> tbl_Trnr_Job_Exp_Info { get; set; }
        public virtual DbSet<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info { get; set; }
        public virtual DbSet<tbl_Trnr_Skill_Set> tbl_Trnr_Skill_Set { get; set; }
        public virtual DbSet<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload { get; set; }
        public virtual DbSet<tbl_Adm_Info> tbl_Adm_Info { get; set; }
    }
}
