//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Trnr_Personal_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Trnr_Personal_Info()
        {
            this.tbl_Trnr_Job_Exp_Info = new HashSet<tbl_Trnr_Job_Exp_Info>();
            this.tbl_Trnr_Skill_Set = new HashSet<tbl_Trnr_Skill_Set>();
        }
    
        public long ID { get; set; }
        public long Login_Id { get; set; }
        public byte[] First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Alias { get; set; }
        public long Gender { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Mobile_Number { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Pin_Code { get; set; }
        public long State { get; set; }
        public long Country { get; set; }
        public long Qualification { get; set; }
        public string Photo { get; set; }
        public string Secondary_Email { get; set; }
        public string About_Me { get; set; }
        public bool Is_SME { get; set; }
        public Nullable<long> SME_Id { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public System.DateTime Updated_Date { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Login tbl_Login2 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master1 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Job_Exp_Info> tbl_Trnr_Job_Exp_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Skill_Set> tbl_Trnr_Skill_Set { get; set; }
    }
}
