//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stud_Personal_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Stud_Personal_Info()
        {
            this.tbl_Emp_Attempted_Stud = new HashSet<tbl_Emp_Attempted_Stud>();
            this.tbl_Stud_Assignment_Answers = new HashSet<tbl_Stud_Assignment_Answers>();
            this.tbl_Stud_Assignment_Info = new HashSet<tbl_Stud_Assignment_Info>();
            this.tbl_Stud_Assignment_Project_Answers = new HashSet<tbl_Stud_Assignment_Project_Answers>();
            this.tbl_Stud_Certificate = new HashSet<tbl_Stud_Certificate>();
            this.tbl_Stud_Course_Regd = new HashSet<tbl_Stud_Course_Regd>();
            this.tbl_Stud_Favourites_Vd = new HashSet<tbl_Stud_Favourites_Vd>();
            this.tbl_Stud_Job_Exp_Info = new HashSet<tbl_Stud_Job_Exp_Info>();
            this.tbl_Stud_Notes = new HashSet<tbl_Stud_Notes>();
            this.tbl_Stud_Resume = new HashSet<tbl_Stud_Resume>();
            this.tbl_Stud_Resume1 = new HashSet<tbl_Stud_Resume>();
            this.tbl_Stud_Resume2 = new HashSet<tbl_Stud_Resume>();
            this.tbl_Stud_Skill_Set = new HashSet<tbl_Stud_Skill_Set>();
            this.tbl_Stud_Viewed_Vd = new HashSet<tbl_Stud_Viewed_Vd>();
            this.tbl_Trnr_Assignment_Master = new HashSet<tbl_Trnr_Assignment_Master>();
        }
    
        public long ID { get; set; }
        public long Login_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Alias { get; set; }
        public long Gender { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Mobile_Number { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Pin_Code { get; set; }
        public long State { get; set; }
        public long Country { get; set; }
        public long Qualification { get; set; }
        public string Photo { get; set; }
        public string Company_Name { get; set; }
        public string Secondary_Email { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public System.DateTime Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Attempted_Stud> tbl_Emp_Attempted_Stud { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Login tbl_Login2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Answers> tbl_Stud_Assignment_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Info> tbl_Stud_Assignment_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Project_Answers> tbl_Stud_Assignment_Project_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Certificate> tbl_Stud_Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Course_Regd> tbl_Stud_Course_Regd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Favourites_Vd> tbl_Stud_Favourites_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Job_Exp_Info> tbl_Stud_Job_Exp_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Notes> tbl_Stud_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Resume> tbl_Stud_Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Resume> tbl_Stud_Resume1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Resume> tbl_Stud_Resume2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Skill_Set> tbl_Stud_Skill_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Viewed_Vd> tbl_Stud_Viewed_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Master> tbl_Trnr_Assignment_Master { get; set; }
    }
}
