//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Trnr_Assignment_Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Trnr_Assignment_Questions()
        {
            this.tbl_Stud_Assignment_Answers = new HashSet<tbl_Stud_Assignment_Answers>();
            this.tbl_Stud_Assignment_Project_Answers = new HashSet<tbl_Stud_Assignment_Project_Answers>();
        }
    
        public long ID { get; set; }
        public long Assignment_Id { get; set; }
        public long Question_Type { get; set; }
        public string Question_Name { get; set; }
        public string Option_A { get; set; }
        public string Option_B { get; set; }
        public string Option_C { get; set; }
        public string Option_D { get; set; }
        public string Answer { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Answers> tbl_Stud_Assignment_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Project_Answers> tbl_Stud_Assignment_Project_Answers { get; set; }
        public virtual tbl_Trnr_Assignment_Master tbl_Trnr_Assignment_Master { get; set; }
    }
}
