//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stud_Skill_Set
    {
        public long ID { get; set; }
        public long Student_Id { get; set; }
        public long Skill_Id { get; set; }
        public long Experience { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master1 { get; set; }
        public virtual tbl_Stud_Personal_Info tbl_Stud_Personal_Info { get; set; }
    }
}
