//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emp_Info
    {
        public long ID { get; set; }
        public long Login_Id { get; set; }
        public string Company_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Alias { get; set; }
        public long Gender { get; set; }
        public System.DateTime Date_Of_Joining { get; set; }
        public string Contact_Number { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Pin_Code { get; set; }
        public long State { get; set; }
        public long Country { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Login tbl_Login2 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master1 { get; set; }
    }
}
