//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fee_Payment_Info
    {
        public long ID { get; set; }
        public long Login_Id { get; set; }
        public long Course_Id { get; set; }
        public decimal Course_Fee { get; set; }
        public decimal Paid_Fee { get; set; }
        public string Payment_Proof { get; set; }
        public string Transaction_Id { get; set; }
        public bool Is_Approved { get; set; }
        public long Approved_By { get; set; }
        public string Remarks { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tbl_Course_Detail tbl_Course_Detail { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Login tbl_Login2 { get; set; }
    }
}
