//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emp_Job_Ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Emp_Job_Ad()
        {
            this.tbl_Emp_Attempted_Stud = new HashSet<tbl_Emp_Attempted_Stud>();
            this.tbl_Emp_Job_Ad_Skills = new HashSet<tbl_Emp_Job_Ad_Skills>();
        }
    
        public long ID { get; set; }
        public long Company_Id { get; set; }
        public string Opening_Type { get; set; }
        public int No_Of_Positions { get; set; }
        public long Package_Range { get; set; }
        public long Experience_Range { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Attempted_Stud> tbl_Emp_Attempted_Stud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad_Skills> tbl_Emp_Job_Ad_Skills { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Login tbl_Login2 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master1 { get; set; }
    }
}
