//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Login()
        {
            this.tbl_Fee_Payment_Info = new HashSet<tbl_Fee_Payment_Info>();
            this.tbl_Fee_Payment_Info1 = new HashSet<tbl_Fee_Payment_Info>();
            this.tbl_Fee_Payment_Info2 = new HashSet<tbl_Fee_Payment_Info>();
            this.tbl_Course_Detail = new HashSet<tbl_Course_Detail>();
            this.tbl_Course_Detail1 = new HashSet<tbl_Course_Detail>();
            this.tbl_Course_Video = new HashSet<tbl_Course_Video>();
            this.tbl_Course_Video1 = new HashSet<tbl_Course_Video>();
            this.tbl_Emp_Attempted_Stud = new HashSet<tbl_Emp_Attempted_Stud>();
            this.tbl_Emp_Attempted_Stud1 = new HashSet<tbl_Emp_Attempted_Stud>();
            this.tbl_Emp_Info = new HashSet<tbl_Emp_Info>();
            this.tbl_Emp_Info1 = new HashSet<tbl_Emp_Info>();
            this.tbl_Emp_Info2 = new HashSet<tbl_Emp_Info>();
            this.tbl_Emp_Job_Ad = new HashSet<tbl_Emp_Job_Ad>();
            this.tbl_Emp_Job_Ad1 = new HashSet<tbl_Emp_Job_Ad>();
            this.tbl_Emp_Job_Ad2 = new HashSet<tbl_Emp_Job_Ad>();
            this.tbl_Emp_Job_Ad_Skills = new HashSet<tbl_Emp_Job_Ad_Skills>();
            this.tbl_Emp_Job_Ad_Skills1 = new HashSet<tbl_Emp_Job_Ad_Skills>();
            this.tbl_Adm_Info = new HashSet<tbl_Adm_Info>();
            this.tbl_Adm_Info1 = new HashSet<tbl_Adm_Info>();
            this.tbl_Adm_Info2 = new HashSet<tbl_Adm_Info>();
            this.tbl_Master = new HashSet<tbl_Master>();
            this.tbl_Master1 = new HashSet<tbl_Master>();
            this.tbl_Stud_Assignment_Answers = new HashSet<tbl_Stud_Assignment_Answers>();
            this.tbl_Stud_Assignment_Answers1 = new HashSet<tbl_Stud_Assignment_Answers>();
            this.tbl_Stud_Assignment_Info = new HashSet<tbl_Stud_Assignment_Info>();
            this.tbl_Stud_Assignment_Info1 = new HashSet<tbl_Stud_Assignment_Info>();
            this.tbl_Stud_Assignment_Project_Answers = new HashSet<tbl_Stud_Assignment_Project_Answers>();
            this.tbl_Stud_Assignment_Project_Answers1 = new HashSet<tbl_Stud_Assignment_Project_Answers>();
            this.tbl_Stud_Certificate = new HashSet<tbl_Stud_Certificate>();
            this.tbl_Stud_Certificate1 = new HashSet<tbl_Stud_Certificate>();
            this.tbl_Stud_Course_Regd = new HashSet<tbl_Stud_Course_Regd>();
            this.tbl_Stud_Course_Regd1 = new HashSet<tbl_Stud_Course_Regd>();
            this.tbl_Stud_Favourites_Vd = new HashSet<tbl_Stud_Favourites_Vd>();
            this.tbl_Stud_Favourites_Vd1 = new HashSet<tbl_Stud_Favourites_Vd>();
            this.tbl_Stud_Job_Exp_Info = new HashSet<tbl_Stud_Job_Exp_Info>();
            this.tbl_Stud_Job_Exp_Info1 = new HashSet<tbl_Stud_Job_Exp_Info>();
            this.tbl_Stud_Notes = new HashSet<tbl_Stud_Notes>();
            this.tbl_Stud_Notes1 = new HashSet<tbl_Stud_Notes>();
            this.tbl_Stud_Personal_Info = new HashSet<tbl_Stud_Personal_Info>();
            this.tbl_Stud_Personal_Info1 = new HashSet<tbl_Stud_Personal_Info>();
            this.tbl_Stud_Personal_Info2 = new HashSet<tbl_Stud_Personal_Info>();
            this.tbl_Stud_Skill_Set = new HashSet<tbl_Stud_Skill_Set>();
            this.tbl_Stud_Skill_Set1 = new HashSet<tbl_Stud_Skill_Set>();
            this.tbl_Stud_Viewed_Vd = new HashSet<tbl_Stud_Viewed_Vd>();
            this.tbl_Stud_Viewed_Vd1 = new HashSet<tbl_Stud_Viewed_Vd>();
            this.tbl_Sub_Master = new HashSet<tbl_Sub_Master>();
            this.tbl_Sub_Master1 = new HashSet<tbl_Sub_Master>();
            this.tbl_Trnr_Assignment_Master = new HashSet<tbl_Trnr_Assignment_Master>();
            this.tbl_Trnr_Assignment_Master1 = new HashSet<tbl_Trnr_Assignment_Master>();
            this.tbl_Trnr_Assignment_Questions = new HashSet<tbl_Trnr_Assignment_Questions>();
            this.tbl_Trnr_Assignment_Questions1 = new HashSet<tbl_Trnr_Assignment_Questions>();
            this.tbl_Trnr_Job_Exp_Info = new HashSet<tbl_Trnr_Job_Exp_Info>();
            this.tbl_Trnr_Job_Exp_Info1 = new HashSet<tbl_Trnr_Job_Exp_Info>();
            this.tbl_Trnr_Personal_Info = new HashSet<tbl_Trnr_Personal_Info>();
            this.tbl_Trnr_Personal_Info1 = new HashSet<tbl_Trnr_Personal_Info>();
            this.tbl_Trnr_Personal_Info2 = new HashSet<tbl_Trnr_Personal_Info>();
            this.tbl_Trnr_Skill_Set = new HashSet<tbl_Trnr_Skill_Set>();
            this.tbl_Trnr_Skill_Set1 = new HashSet<tbl_Trnr_Skill_Set>();
            this.tbl_Trnr_Video_Upload = new HashSet<tbl_Trnr_Video_Upload>();
            this.tbl_Trnr_Video_Upload1 = new HashSet<tbl_Trnr_Video_Upload>();
            this.tbl_Trnr_Video_Upload2 = new HashSet<tbl_Trnr_Video_Upload>();
        }
    
        public long ID { get; set; }
        public string User_ID { get; set; }
        public string Password { get; set; }
        public bool Is_Email_Verified { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<long> Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public long Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fee_Payment_Info> tbl_Fee_Payment_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fee_Payment_Info> tbl_Fee_Payment_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fee_Payment_Info> tbl_Fee_Payment_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Detail> tbl_Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Detail> tbl_Course_Detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Video> tbl_Course_Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Video> tbl_Course_Video1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Attempted_Stud> tbl_Emp_Attempted_Stud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Attempted_Stud> tbl_Emp_Attempted_Stud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Info> tbl_Emp_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Info> tbl_Emp_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Info> tbl_Emp_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad> tbl_Emp_Job_Ad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad> tbl_Emp_Job_Ad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad> tbl_Emp_Job_Ad2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad_Skills> tbl_Emp_Job_Ad_Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad_Skills> tbl_Emp_Job_Ad_Skills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adm_Info> tbl_Adm_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adm_Info> tbl_Adm_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adm_Info> tbl_Adm_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Master> tbl_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Master> tbl_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Answers> tbl_Stud_Assignment_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Answers> tbl_Stud_Assignment_Answers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Info> tbl_Stud_Assignment_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Info> tbl_Stud_Assignment_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Project_Answers> tbl_Stud_Assignment_Project_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Project_Answers> tbl_Stud_Assignment_Project_Answers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Certificate> tbl_Stud_Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Certificate> tbl_Stud_Certificate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Course_Regd> tbl_Stud_Course_Regd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Course_Regd> tbl_Stud_Course_Regd1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Favourites_Vd> tbl_Stud_Favourites_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Favourites_Vd> tbl_Stud_Favourites_Vd1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Job_Exp_Info> tbl_Stud_Job_Exp_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Job_Exp_Info> tbl_Stud_Job_Exp_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Notes> tbl_Stud_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Notes> tbl_Stud_Notes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Personal_Info> tbl_Stud_Personal_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Personal_Info> tbl_Stud_Personal_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Personal_Info> tbl_Stud_Personal_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Skill_Set> tbl_Stud_Skill_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Skill_Set> tbl_Stud_Skill_Set1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Viewed_Vd> tbl_Stud_Viewed_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Viewed_Vd> tbl_Stud_Viewed_Vd1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sub_Master> tbl_Sub_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sub_Master> tbl_Sub_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Master> tbl_Trnr_Assignment_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Master> tbl_Trnr_Assignment_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Questions> tbl_Trnr_Assignment_Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Questions> tbl_Trnr_Assignment_Questions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Job_Exp_Info> tbl_Trnr_Job_Exp_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Job_Exp_Info> tbl_Trnr_Job_Exp_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Skill_Set> tbl_Trnr_Skill_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Skill_Set> tbl_Trnr_Skill_Set1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload2 { get; set; }
    }
}
