//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sub_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sub_Master()
        {
            this.tbl_Course_Detail = new HashSet<tbl_Course_Detail>();
            this.tbl_Course_Detail1 = new HashSet<tbl_Course_Detail>();
            this.tbl_Course_Detail2 = new HashSet<tbl_Course_Detail>();
            this.tbl_Course_Video = new HashSet<tbl_Course_Video>();
            this.tbl_Emp_Attempted_Stud = new HashSet<tbl_Emp_Attempted_Stud>();
            this.tbl_Emp_Info = new HashSet<tbl_Emp_Info>();
            this.tbl_Emp_Info1 = new HashSet<tbl_Emp_Info>();
            this.tbl_Emp_Job_Ad = new HashSet<tbl_Emp_Job_Ad>();
            this.tbl_Emp_Job_Ad1 = new HashSet<tbl_Emp_Job_Ad>();
            this.tbl_Emp_Job_Ad_Skills = new HashSet<tbl_Emp_Job_Ad_Skills>();
            this.tbl_Adm_Info = new HashSet<tbl_Adm_Info>();
            this.tbl_Adm_Info1 = new HashSet<tbl_Adm_Info>();
            this.tbl_Adm_Info2 = new HashSet<tbl_Adm_Info>();
            this.tbl_Stud_Assignment_Info = new HashSet<tbl_Stud_Assignment_Info>();
            this.tbl_Stud_Skill_Set = new HashSet<tbl_Stud_Skill_Set>();
            this.tbl_Stud_Skill_Set1 = new HashSet<tbl_Stud_Skill_Set>();
            this.tbl_Trnr_Assignment_Master = new HashSet<tbl_Trnr_Assignment_Master>();
            this.tbl_Trnr_Assignment_Questions = new HashSet<tbl_Trnr_Assignment_Questions>();
            this.tbl_Trnr_Personal_Info = new HashSet<tbl_Trnr_Personal_Info>();
            this.tbl_Trnr_Personal_Info1 = new HashSet<tbl_Trnr_Personal_Info>();
            this.tbl_Trnr_Personal_Info2 = new HashSet<tbl_Trnr_Personal_Info>();
            this.tbl_Trnr_Skill_Set = new HashSet<tbl_Trnr_Skill_Set>();
            this.tbl_Trnr_Video_Upload = new HashSet<tbl_Trnr_Video_Upload>();
        }
    
        public long ID { get; set; }
        public string Sub_Master_Key { get; set; }
        public string Sub_Master_Value { get; set; }
        public long Master_Id { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<long> Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Detail> tbl_Course_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Detail> tbl_Course_Detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Detail> tbl_Course_Detail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Video> tbl_Course_Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Attempted_Stud> tbl_Emp_Attempted_Stud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Info> tbl_Emp_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Info> tbl_Emp_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad> tbl_Emp_Job_Ad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad> tbl_Emp_Job_Ad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp_Job_Ad_Skills> tbl_Emp_Job_Ad_Skills { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Master tbl_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adm_Info> tbl_Adm_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adm_Info> tbl_Adm_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Adm_Info> tbl_Adm_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Assignment_Info> tbl_Stud_Assignment_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Skill_Set> tbl_Stud_Skill_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Skill_Set> tbl_Stud_Skill_Set1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Master> tbl_Trnr_Assignment_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Questions> tbl_Trnr_Assignment_Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Personal_Info> tbl_Trnr_Personal_Info2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Skill_Set> tbl_Trnr_Skill_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload { get; set; }
    }
}
