//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Course_Detail()
        {
            this.tbl_Fee_Payment_Info = new HashSet<tbl_Fee_Payment_Info>();
            this.tbl_Course_Video = new HashSet<tbl_Course_Video>();
            this.tbl_Stud_Course_Regd = new HashSet<tbl_Stud_Course_Regd>();
            this.tbl_Stud_Favourites_Vd = new HashSet<tbl_Stud_Favourites_Vd>();
            this.tbl_Stud_Notes = new HashSet<tbl_Stud_Notes>();
            this.tbl_Trnr_Assignment_Master = new HashSet<tbl_Trnr_Assignment_Master>();
            this.tbl_Trnr_Video_Upload = new HashSet<tbl_Trnr_Video_Upload>();
        }
    
        public long ID { get; set; }
        public string Course_Name { get; set; }
        public string Course_Image { get; set; }
        public long Skill_Category { get; set; }
        public long Course_Level { get; set; }
        public long Course_Type { get; set; }
        public decimal Course_Fee { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Fee_Payment_Info> tbl_Fee_Payment_Info { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master1 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Course_Video> tbl_Course_Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Course_Regd> tbl_Stud_Course_Regd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Favourites_Vd> tbl_Stud_Favourites_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Notes> tbl_Stud_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Assignment_Master> tbl_Trnr_Assignment_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload { get; set; }
    }
}
