//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Course_Video()
        {
            this.tbl_Stud_Favourites_Vd = new HashSet<tbl_Stud_Favourites_Vd>();
            this.tbl_Stud_Notes = new HashSet<tbl_Stud_Notes>();
            this.tbl_Stud_Viewed_Vd = new HashSet<tbl_Stud_Viewed_Vd>();
            this.tbl_Trnr_Video_Upload = new HashSet<tbl_Trnr_Video_Upload>();
        }
    
        public long ID { get; set; }
        public long Course_Id { get; set; }
        public string Video_Name { get; set; }
        public string Display_Name { get; set; }
        public string Description { get; set; }
        public string ThumbNail { get; set; }
        public long Video_Type { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tbl_Course_Detail tbl_Course_Detail { get; set; }
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Login tbl_Login1 { get; set; }
        public virtual tbl_Sub_Master tbl_Sub_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Favourites_Vd> tbl_Stud_Favourites_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Notes> tbl_Stud_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stud_Viewed_Vd> tbl_Stud_Viewed_Vd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Trnr_Video_Upload> tbl_Trnr_Video_Upload { get; set; }
    }
}
