//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseManagement_DBLayer.EntityRelated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stud_Resume
    {
        public long ID { get; set; }
        public Nullable<long> Student_Id { get; set; }
        public string Resume { get; set; }
        public bool Is_Primary { get; set; }
        public bool Is_Active { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual tbl_Stud_Personal_Info tbl_Stud_Personal_Info { get; set; }
        public virtual tbl_Stud_Personal_Info tbl_Stud_Personal_Info1 { get; set; }
        public virtual tbl_Stud_Personal_Info tbl_Stud_Personal_Info2 { get; set; }
    }
}
